# Generated by Django 3.2.9 on 2021-11-09 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_private', models.BooleanField()),
                ('private_key', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
            ],
        ),
        migrations.CreateModel(
            name='performances',
            fields=[
                ('performance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('streaming_method', models.SmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('ticket_available_flag', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.events')),
            ],
        ),
        migrations.CreateModel(
            name='event_authorized_users',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('event_id', 'user_id')},
            },
        ),
    ]
