# Generated by Django 3.2.9 on 2021-11-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event_authorized_users',
        ),
        migrations.RemoveField(
            model_name='performances',
            name='event_id',
        ),
    ]
