# Generated by Django 3.2.9 on 2021-11-10 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_clients'),
        ('event', '0002_auto_20211110_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Live stream event'), (2, 'Offline event')]),
        ),
        migrations.AlterModelTable(
            name='events',
            table='events',
        ),
        migrations.DeleteModel(
            name='performances',
        ),
    ]
