# Generated by Django 3.2.9 on 2021-11-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20211111_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_paths',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
