# Generated by Django 3.2.9 on 2021-11-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20211118_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawwings',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_elected', models.BooleanField()),
                ('is_purchased', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
