# Generated by Django 3.2.9 on 2021-11-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20211110_0842'),
        ('user', '0002_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
