# Generated by Django 3.2.9 on 2021-11-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('user_type', models.SmallIntegerField(choices=[(1, 'General user'), (2, 'Host user')])),
                ('login_type', models.CharField(choices=[(1, 'EMAIL'), (2, 'INSTAGRAM'), (3, 'FACEBOOK'), (4, 'TWITTER')], max_length=45)),
                ('creat_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterField(
            model_name='clients',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
