# Generated by Django 3.2.9 on 2021-11-11 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211111_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='creat_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='update_at',
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 11, 7, 57, 46, 912698, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
